-- Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
-- SPDX-License-Identifier: MIT-0
--
-- test-migration.sql
--
-- Sample migration file with intentional DSQL-incompatible patterns.
-- Use with dsql-lint to demonstrate detection and auto-fix capabilities.
--
-- Usage:
--   dsql-lint test-migration.sql
--   dsql-lint --fix test-migration.sql

-- ---------------------------------------------------------------------------
-- 1. SERIAL / BIGSERIAL / SMALLSERIAL — not supported in DSQL
--    Fix: BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)
-- ---------------------------------------------------------------------------

CREATE TABLE customers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoices (
    id BIGSERIAL PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    total DECIMAL(12, 2) NOT NULL,
    issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE line_items (
    id SMALLSERIAL PRIMARY KEY,
    invoice_id INTEGER NOT NULL,
    description VARCHAR(500) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL
);

-- ---------------------------------------------------------------------------
-- 2. JSON / JSONB columns — not supported in DSQL
--    Fix: TEXT (store serialized JSON as a string)
-- ---------------------------------------------------------------------------

CREATE TABLE events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type VARCHAR(100) NOT NULL,
    payload JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    action VARCHAR(100) NOT NULL,
    details JSONB,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 3. FOREIGN KEY constraints — not supported in DSQL
--    Fix: remove constraint, enforce referential integrity in application code
-- ---------------------------------------------------------------------------

CREATE TABLE departments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL
);

CREATE TABLE employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    department_id UUID REFERENCES departments(id),
    manager_id UUID,
    CONSTRAINT fk_manager FOREIGN KEY (manager_id) REFERENCES employees(id)
);

-- ---------------------------------------------------------------------------
-- 4. Synchronous CREATE INDEX — not supported in DSQL
--    Fix: CREATE INDEX ASYNC
-- ---------------------------------------------------------------------------

CREATE INDEX idx_customers_email ON customers(email);

CREATE INDEX idx_invoices_customer ON invoices(customer_id);

CREATE INDEX idx_employees_dept ON employees(department_id);

-- ---------------------------------------------------------------------------
-- 5. CREATE INDEX CONCURRENTLY — not supported in DSQL
--    Fix: CREATE INDEX ASYNC
-- ---------------------------------------------------------------------------

CREATE INDEX CONCURRENTLY idx_events_type ON events(event_type);

-- ---------------------------------------------------------------------------
-- 6. TEMPORARY TABLE — not supported in DSQL
--    Fix: use a regular table or application-level caching
-- ---------------------------------------------------------------------------

CREATE TEMPORARY TABLE temp_import (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    raw_data TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- 7. TRUNCATE — not supported in DSQL
--    Fix: use DELETE FROM instead
-- ---------------------------------------------------------------------------

TRUNCATE TABLE temp_import;

-- ---------------------------------------------------------------------------
-- 8. ALTER TABLE ADD COLUMN with DEFAULT or NOT NULL — not supported in DSQL
--    Fix: ADD COLUMN without constraints, then backfill with UPDATE
-- ---------------------------------------------------------------------------

ALTER TABLE customers ADD COLUMN status VARCHAR(50) DEFAULT 'active' NOT NULL;

-- ---------------------------------------------------------------------------
-- 9. ALTER TABLE DROP COLUMN — not supported in DSQL
--     Fix: recreate the table without the column, then migrate data
-- ---------------------------------------------------------------------------

ALTER TABLE customers DROP COLUMN created_at;

-- ---------------------------------------------------------------------------
-- 10. ALTER TABLE ADD FOREIGN KEY — not supported in DSQL
--     Fix: remove constraint, enforce in application code
-- ---------------------------------------------------------------------------

ALTER TABLE line_items ADD CONSTRAINT fk_invoice
    FOREIGN KEY (invoice_id) REFERENCES invoices(id);

-- ---------------------------------------------------------------------------
-- 11. CREATE SEQUENCE with invalid CACHE — DSQL requires CACHE 1 or >= 65536
--     Fix: set CACHE 1
-- ---------------------------------------------------------------------------

CREATE SEQUENCE order_seq AS INTEGER CACHE 100;

-- ---------------------------------------------------------------------------
-- 12. Identity column without CACHE clause — DSQL requires explicit CACHE
--     Fix: add CACHE 1
-- ---------------------------------------------------------------------------

CREATE TABLE tickets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    subject VARCHAR(500) NOT NULL
);

-- ---------------------------------------------------------------------------
-- 13. Identity column with non-BIGINT type — DSQL requires BIGINT
--     Fix: change to BIGINT
-- ---------------------------------------------------------------------------

CREATE TABLE counters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
    label VARCHAR(255) NOT NULL
);

-- ---------------------------------------------------------------------------
-- 14. Transaction isolation level — DSQL only supports REPEATABLE READ
--     Fix: change to REPEATABLE READ
-- ---------------------------------------------------------------------------

BEGIN ISOLATION LEVEL SERIALIZABLE;

-- ---------------------------------------------------------------------------
-- 15. Unsupported statements
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE DATABASE analytics;

-- ---------------------------------------------------------------------------
-- 16. PARTITION BY — not supported in DSQL
--     Fix: remove clause, DSQL manages distribution automatically
-- ---------------------------------------------------------------------------

CREATE TABLE metrics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    recorded_at TIMESTAMP NOT NULL,
    value DECIMAL(10, 2) NOT NULL
) PARTITION BY RANGE (recorded_at);

-- ---------------------------------------------------------------------------
-- 17. Expression index — not supported in DSQL
--     Fix: add a stored computed column and index that instead
-- ---------------------------------------------------------------------------

CREATE INDEX idx_customers_lower_email ON customers(LOWER(email));

-- ---------------------------------------------------------------------------
-- 18. Partial index — not supported in DSQL
--     Fix: create a full index instead, or filter in queries
-- ---------------------------------------------------------------------------

CREATE INDEX idx_invoices_unpaid ON invoices(customer_id) WHERE total > 0;

-- ---------------------------------------------------------------------------
-- 19. ALTER TABLE operations — various unsupported operations in DSQL
-- ---------------------------------------------------------------------------

ALTER TABLE customers ALTER COLUMN name TYPE TEXT;

ALTER TABLE customers ALTER COLUMN email SET NOT NULL;

ALTER TABLE customers DROP CONSTRAINT customers_email_key;
